apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderflow-backend
  namespace: orderflow
  labels:
    app: orderflow-backend
    component: api
    version: v2.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orderflow-backend
  template:
    metadata:
      labels:
        app: orderflow-backend
        component: api
        version: v2.0.0
    spec:
      containers:
      - name: orderflow-backend
        image: orderflow/backend:v2.0.0
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: orderflow-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: orderflow-config
              key: PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: orderflow-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: orderflow-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: orderflow-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: orderflow-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: orderflow-secrets
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: orderflow-secrets
              key: JWT_SECRET
        - name: PAYMENT_GATEWAY_API_KEY
          valueFrom:
            secretKeyRef:
              name: orderflow-secrets
              key: PAYMENT_GATEWAY_API_KEY
        - name: PAYMENT_GATEWAY_SECRET
          valueFrom:
            secretKeyRef:
              name: orderflow-secrets
              key: PAYMENT_GATEWAY_SECRET
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: orderflow-config
              key: CORS_ORIGIN
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: orderflow-config
              key: LOG_LEVEL
        - name: PAYMENT_GATEWAY_TYPE
          valueFrom:
            configMapKeyRef:
              name: orderflow-config
              key: PAYMENT_GATEWAY_TYPE
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      imagePullSecrets:
      - name: regcred

