apiVersion: v1
kind: ServiceAccount
metadata:
  name: orderflow-service-account
  namespace: orderflow
  labels:
    app: orderflow-backend
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/OrderFlowServiceRole
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orderflow-role
  namespace: orderflow
  labels:
    app: orderflow-backend
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orderflow-role-binding
  namespace: orderflow
  labels:
    app: orderflow-backend
subjects:
- kind: ServiceAccount
  name: orderflow-service-account
  namespace: orderflow
roleRef:
  kind: Role
  name: orderflow-role
  apiGroup: rbac.authorization.k8s.io

